### ISSUE TITLE
Problems running RiboTIE

### ISSUE THREAD

**Issue by DanielAldas** [TRISTAN-ORF/RiboTIE#9]
Hi!
I am having difficulties running RiboTIE. Firts of all, after installing transcript_transformer I tried to run ribotie -h and got "-bash: ribotie: command not found", but I noticed that I can use the riboformer command, so I tried running that instead. 

I ran the example files first (riboformer template.yml), and I got this: 

<img width="1900" alt="Screenshot 2024-05-20 at 3 20 13 PM" src="https://github.com/TRISTAN-ORF/RiboTIE/assets/54075272/98d039fa-f8b6-496a-be1e-daa21fd4ad4f">

The h5 file was the only output generated.

Then I tried with my own data and got the following error:
 
<img width="956" alt="Screenshot 2024-05-20 at 3 24 29 PM" src="https://github.com/TRISTAN-ORF/RiboTIE/assets/54075272/81438278-02d1-4f6a-b653-d01778772a1d">

Do you have any clue what could be causing this error? 

Thanks

**Comment by jdcla** [comment]
You might be running an older version of the tool. Can you confirm the package version.

Sometimes, because some of the dependency constraints, an older version is picked up. I'm trying to improve this, but am having trouble with some outdated tools that I have to replace.

**Comment by DanielAldas** [comment]
Thanks for the quick response.
I am using transcript_transformer version: 0.4.9

**Comment by jdcla** [comment]
This should definitely be v0.8.1 instead. I'm trying to have this solved in the upcoming release.

Trying to force the version might show why it's pulling 0.4.9 instead. Try running

`pip install transcript-transformer=0.8.1`

**Comment by DanielAldas** [comment]
I am using the correct version now. I was able to run RiboTIE with the example data, but I got a similar error when I tried using my own data

<img width="1245" alt="Screenshot 2024-05-21 at 9 36 12 AM" src="https://github.com/TRISTAN-ORF/RiboTIE/assets/54075272/5a0a0fcf-9766-4eb8-8252-3710299fda69">

**Comment by jdcla** [comment]
Seems I never ran across lowercase nucleotides in the fasta file and therefore did not provide support for this. Should be fixed now (v0.8.2). Let me know if everything works and I'll close the issue.

**Comment by DanielAldas** [comment]
I just updated the package and it's running right now. Everything seems fine for now; I will let you know if I found anything else.

Thanks a lot!

**Comment by DanielAldas** [comment]
I just got this error:
`AssertionError: Transcript IDs exist within mapped reads which are not present in the h5 database. Please apply an identical assembly for both setting up this database and mapping the ribosome reads.
`

I double check and I am using the exact same assembly. I don't know what else can be causing this issue

**Comment by jdcla** [comment]
Are you using a bam/sam file with reads mapped to the transcriptome  (rather than the genome?) 

Did parsing the gtf file complete without any errors? You might also try deleting the .h5 database and starting from start.

If you can, feel free to share the assembly file and ribo-seq file with me if you're still encountering errors.

**Comment by DanielAldas** [comment]
I was using the wrong alignment. Thanks for your help!
